# Generated by Django 6.0.5 on 2026-07-07 19:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField(max_length=500)),
                ('interval_minutes', models.PositiveSmallIntegerField(choices=[(1, 'every minute'), (5, 'every 5 minutes'), (15, 'every 15 minutes'), (60, 'every hour')], default=5)),
                ('timeout_seconds', models.PositiveSmallIntegerField(default=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_public', models.BooleanField(default=False, help_text='Expose a public status page for this monitor.')),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('last_status', models.CharField(choices=[('up', 'Up'), ('down', 'Down'), ('unknown', 'Unknown')], default='unknown', max_length=10)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('last_response_ms', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CheckResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ok', models.BooleanField()),
                ('status_code', models.SmallIntegerField(blank=True, null=True)),
                ('response_ms', models.IntegerField(blank=True, null=True)),
                ('error', models.CharField(blank=True, max_length=200)),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='monitors.monitor')),
            ],
            options={
                'ordering': ['-checked_at'],
                'indexes': [models.Index(fields=['monitor', '-checked_at'], name='monitors_ch_monitor_24c7e4_idx')],
            },
        ),
    ]
